"""
Remediation Module for Cyber Essentials Scanner
Generates safe automated fixes and remediation scripts for Windows.
"""

import os
import platform
from typing import Dict, List, Any

POWERSHELL_HEADER = """# Cyber Essentials Remediation Script
# Generated by CE Scanner v0.2.0
# WARNING: Review this script before running. Some changes may require reboot.
# Run as Administrator: Right-click and select "Run as Administrator"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Cyber Essentials Remediation Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as administrator
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "ERROR: This script must be run as Administrator!" -ForegroundColor Red
    Write-Host "Right-click the script and select 'Run as Administrator'" -ForegroundColor Yellow
    pause
    exit 1
}

Write-Host "Running as Administrator - OK" -ForegroundColor Green
Write-Host ""

"""

def generate_screen_lock_fix() -> str:
    """Generate PowerShell script to fix screen lock timeout"""
    return """
# Fix 1: Screen Lock Timeout (5 minutes max for CE compliance)
Write-Host "[1/7] Configuring screen lock timeout..." -ForegroundColor Yellow
try {
    # Set screen lock timeout to 5 minutes (300 seconds)
    powercfg /setacvalueindex SCHEME_CURRENT SUB_VIDEO VIDEOIDLE 300
    powercfg /setdcvalueindex SCHEME_CURRENT SUB_VIDEO VIDEOIDLE 300
    
    # Apply the power scheme
    powercfg /setactive SCHEME_CURRENT
    
    Write-Host "      Screen lock timeout set to 5 minutes - OK" -ForegroundColor Green
} catch {
    Write-Host "      Failed to set screen lock timeout: $_" -ForegroundColor Red
}
Write-Host ""
"""

def generate_password_protection_fix() -> str:
    """Generate PowerShell script to enable password protection on wake"""
    return """
# Fix 2: Password Protection on Wake
Write-Host "[2/7] Enabling password protection on wake..." -ForegroundColor Yellow
try {
    # Enable password protection when computer wakes (AC power)
    powercfg /setacvalueindex SCHEME_CURRENT SUB_NONE CONSOLELOCK 1
    # Enable password protection when computer wakes (Battery power)
    powercfg /setdcvalueindex SCHEME_CURRENT SUB_NONE CONSOLELOCK 1
    
    # Apply the power scheme
    powercfg /setactive SCHEME_CURRENT
    
    Write-Host "      Password protection on wake enabled - OK" -ForegroundColor Green
} catch {
    Write-Host "      Failed to enable password protection: $_" -ForegroundColor Red
}
Write-Host ""
"""

def generate_windows_update_fix() -> str:
    """Generate PowerShell script to check Windows Update"""
    return """
# Fix 3: Windows Update Check
Write-Host "[3/7] Checking Windows Update status..." -ForegroundColor Yellow
try {
    $updateService = Get-Service -Name wuauserv -ErrorAction Stop
    if ($updateService.Status -ne 'Running') {
        Write-Host "      Windows Update service not running. Starting..." -ForegroundColor Yellow
        Start-Service -Name wuauserv
        Write-Host "      Windows Update service started - OK" -ForegroundColor Green
    } else {
        Write-Host "      Windows Update service is running - OK" -ForegroundColor Green
    }
    
    Write-Host "      Opening Windows Update settings..." -ForegroundColor Cyan
    Start-Process "ms-settings:windowsupdate"
    Write-Host "      Please check for and install any pending updates." -ForegroundColor Yellow
} catch {
    Write-Host "      Failed to check Windows Update: $_" -ForegroundColor Red
}
Write-Host ""
"""

def generate_firewall_fix() -> str:
    """Generate PowerShell script to enable Windows Firewall"""
    return """
# Fix 4: Windows Firewall
Write-Host "[4/7] Checking Windows Firewall..." -ForegroundColor Yellow
try {
    $firewallProfiles = @('Domain', 'Private', 'Public')
    foreach ($profile in $firewallProfiles) {
        $status = Get-NetFirewallProfile -Name $profile | Select-Object -ExpandProperty Enabled
        if ($status -eq $false) {
            Write-Host "      Enabling firewall for $profile profile..." -ForegroundColor Yellow
            Set-NetFirewallProfile -Name $profile -Enabled True
            Write-Host "      Firewall enabled for $profile - OK" -ForegroundColor Green
        } else {
            Write-Host "      Firewall already enabled for $profile - OK" -ForegroundColor Green
        }
    }
} catch {
    Write-Host "      Failed to configure firewall: $_" -ForegroundColor Red
}
Write-Host ""
"""

def generate_defender_fix() -> str:
    """Generate PowerShell script to enable Windows Defender"""
    return """
# Fix 5: Windows Defender
Write-Host "[5/7] Checking Windows Defender..." -ForegroundColor Yellow
try {
    $defenderStatus = Get-MpComputerStatus -ErrorAction Stop
    
    if (-not $defenderStatus.RealTimeProtectionEnabled) {
        Write-Host "      Enabling Real-Time Protection..." -ForegroundColor Yellow
        Set-MpPreference -DisableRealtimeMonitoring $false
        Write-Host "      Real-Time Protection enabled - OK" -ForegroundColor Green
    } else {
        Write-Host "      Real-Time Protection already enabled - OK" -ForegroundColor Green
    }
    
    # Ensure Defender is not disabled
    if ($defenderStatus.AntivirusEnabled -eq $false) {
        Write-Host "      WARNING: Windows Defender appears to be disabled by policy" -ForegroundColor Red
        Write-Host "      You may need to re-enable it through Group Policy or remove third-party antivirus" -ForegroundColor Yellow
    }
    
    # Start a quick scan
    Write-Host "      Starting Windows Defender quick scan..." -ForegroundColor Cyan
    Start-MpScan -ScanType QuickScan
    Write-Host "      Quick scan initiated - OK" -ForegroundColor Green
} catch {
    Write-Host "      Failed to configure Windows Defender: $_" -ForegroundColor Red
}
Write-Host ""
"""

def generate_uac_fix() -> str:
    """Generate PowerShell script to enable UAC"""
    return """
# Fix 6: User Account Control (UAC)
Write-Host "[6/7] Checking UAC status..." -ForegroundColor Yellow
try {
    $uacStatus = Get-ItemProperty -Path "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System" -Name "EnableLUA" -ErrorAction Stop
    
    if ($uacStatus.EnableLUA -eq 0) {
        Write-Host "      Enabling UAC..." -ForegroundColor Yellow
        Set-ItemProperty -Path "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System" -Name "EnableLUA" -Value 1
        Write-Host "      UAC enabled - REBOOT REQUIRED" -ForegroundColor Yellow
        $script:rebootRequired = $true
    } else {
        Write-Host "      UAC already enabled - OK" -ForegroundColor Green
    }
} catch {
    Write-Host "      Failed to check UAC status: $_" -ForegroundColor Red
}
Write-Host ""
"""

def generate_auto_update_fix() -> str:
    """Generate PowerShell script to enable automatic updates"""
    return """
# Fix 7: Automatic Updates
Write-Host "[7/7] Configuring automatic updates..." -ForegroundColor Yellow
try {
    # Check current Windows Update settings
    $auKey = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU"
    
    if (Test-Path $auKey) {
        # Enable automatic updates (4 = Auto download and schedule install)
        Set-ItemProperty -Path $auKey -Name "NoAutoUpdate" -Value 0 -ErrorAction SilentlyContinue
        Set-ItemProperty -Path $auKey -Name "AUOptions" -Value 4 -ErrorAction SilentlyContinue
        Write-Host "      Automatic updates configured - OK" -ForegroundColor Green
    } else {
        Write-Host "      Windows Update policy key not found - Using default settings" -ForegroundColor Yellow
    }
} catch {
    Write-Host "      Note: Some settings may require Group Policy configuration" -ForegroundColor Yellow
}
Write-Host ""
"""

def generate_completion_message() -> str:
    """Generate completion message"""
    return """
# Completion
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Remediation Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

if ($script:rebootRequired) {
    Write-Host "IMPORTANT: A system reboot is required to apply all changes." -ForegroundColor Yellow
    Write-Host ""
    $response = Read-Host "Would you like to reboot now? (Y/N)"
    if ($response -match "^[Yy]") {
        Write-Host "Rebooting system in 10 seconds..." -ForegroundColor Yellow
        shutdown /r /t 10
    } else {
        Write-Host "Please reboot your computer at your earliest convenience." -ForegroundColor Yellow
    }
} else {
    Write-Host "All fixes applied successfully. No reboot required." -ForegroundColor Green
}

Write-Host ""
Write-Host "Run the scanner again to verify fixes:" -ForegroundColor Cyan
Write-Host "  python -m scanner.main" -ForegroundColor White
Write-Host ""
pause
"""

def generate_remediation_script(scan_report: Dict[str, Any], output_path: str = "remediation.ps1") -> str:
    """
    Generate a PowerShell remediation script based on scan results.
    
    Args:
        scan_report: Parsed JSON scan report
        output_path: Path to save the remediation script
    
    Returns:
        Path to generated script
    """
    if platform.system() != "Windows":
        raise NotImplementedError("Remediation scripts are currently only supported on Windows")
    
    script_content = POWERSHELL_HEADER
    script_content += "\n# Initialize reboot flag\n$script:rebootRequired = $false\n"
    
    # Analyze report and add appropriate fixes
    controls = {c["name"]: c for c in scan_report.get("controls", [])}
    
    # Always include these basic fixes
    script_content += generate_screen_lock_fix()
    script_content += generate_password_protection_fix()
    script_content += generate_windows_update_fix()
    
    # Add conditional fixes based on failures
    if "Firewalls" in controls and controls["Firewalls"].get("status") != "pass":
        script_content += generate_firewall_fix()
    
    if "Malware Protection" in controls and controls["Malware Protection"].get("status") != "pass":
        script_content += generate_defender_fix()
    
    if "Access Control" in controls:
        script_content += generate_uac_fix()
    
    script_content += generate_auto_update_fix()
    script_content += generate_completion_message()
    
    # Write script to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(script_content)
    
    return output_path

def get_remediation_recommendations(scan_report: Dict[str, Any]) -> List[str]:
    """
    Get a list of manual remediation recommendations based on scan results.
    
    Args:
        scan_report: Parsed JSON scan report
    
    Returns:
        List of recommendation strings
    """
    recommendations = []
    controls = scan_report.get("controls", [])
    
    for control in controls:
        if control.get("status") in ["fail", "warn"]:
            control_recommendations = control.get("recommendations", [])
            recommendations.extend(control_recommendations)
    
    return recommendations
