# Cyber Essentials Remediation Script
# Generated by CE Scanner v0.2.0
# WARNING: Review this script before running. Some changes may require reboot.
# Run as Administrator: Right-click and select "Run as Administrator"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Cyber Essentials Remediation Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as administrator
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "ERROR: This script must be run as Administrator!" -ForegroundColor Red
    Write-Host "Right-click the script and select 'Run as Administrator'" -ForegroundColor Yellow
    pause
    exit 1
}

Write-Host "Running as Administrator - OK" -ForegroundColor Green
Write-Host ""


# Initialize reboot flag
$script:rebootRequired = $false

# Fix 1: Screen Lock Timeout (5 minutes max for CE compliance)
Write-Host "[1/7] Configuring screen lock timeout..." -ForegroundColor Yellow
try {
    # Set screen lock timeout to 5 minutes (300 seconds)
    powercfg /setacvalueindex SCHEME_CURRENT SUB_VIDEO VIDEOIDLE 300
    powercfg /setdcvalueindex SCHEME_CURRENT SUB_VIDEO VIDEOIDLE 300
    
    # Apply the power scheme
    powercfg /setactive SCHEME_CURRENT
    
    Write-Host "      Screen lock timeout set to 5 minutes - OK" -ForegroundColor Green
} catch {
    Write-Host "      Failed to set screen lock timeout: $_" -ForegroundColor Red
}
Write-Host ""

# Fix 2: Password Protection on Wake
Write-Host "[2/7] Enabling password protection on wake..." -ForegroundColor Yellow
try {
    # Enable password protection when computer wakes (AC power)
    powercfg /setacvalueindex SCHEME_CURRENT SUB_NONE CONSOLELOCK 1
    # Enable password protection when computer wakes (Battery power)
    powercfg /setdcvalueindex SCHEME_CURRENT SUB_NONE CONSOLELOCK 1
    
    # Apply the power scheme
    powercfg /setactive SCHEME_CURRENT
    
    Write-Host "      Password protection on wake enabled - OK" -ForegroundColor Green
} catch {
    Write-Host "      Failed to enable password protection: $_" -ForegroundColor Red
}
Write-Host ""

# Fix 3: Windows Update Check
Write-Host "[3/7] Checking Windows Update status..." -ForegroundColor Yellow
try {
    $updateService = Get-Service -Name wuauserv -ErrorAction Stop
    if ($updateService.Status -ne 'Running') {
        Write-Host "      Windows Update service not running. Starting..." -ForegroundColor Yellow
        Start-Service -Name wuauserv
        Write-Host "      Windows Update service started - OK" -ForegroundColor Green
    } else {
        Write-Host "      Windows Update service is running - OK" -ForegroundColor Green
    }
    
    Write-Host "      Opening Windows Update settings..." -ForegroundColor Cyan
    Start-Process "ms-settings:windowsupdate"
    Write-Host "      Please check for and install any pending updates." -ForegroundColor Yellow
} catch {
    Write-Host "      Failed to check Windows Update: $_" -ForegroundColor Red
}
Write-Host ""

# Fix 7: Automatic Updates
Write-Host "[7/7] Configuring automatic updates..." -ForegroundColor Yellow
try {
    # Check current Windows Update settings
    $auKey = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"
    
    if (Test-Path $auKey) {
        # Enable automatic updates (4 = Auto download and schedule install)
        Set-ItemProperty -Path $auKey -Name "NoAutoUpdate" -Value 0 -ErrorAction SilentlyContinue
        Set-ItemProperty -Path $auKey -Name "AUOptions" -Value 4 -ErrorAction SilentlyContinue
        Write-Host "      Automatic updates configured - OK" -ForegroundColor Green
    } else {
        Write-Host "      Windows Update policy key not found - Using default settings" -ForegroundColor Yellow
    }
} catch {
    Write-Host "      Note: Some settings may require Group Policy configuration" -ForegroundColor Yellow
}
Write-Host ""

# Completion
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Remediation Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

if ($script:rebootRequired) {
    Write-Host "IMPORTANT: A system reboot is required to apply all changes." -ForegroundColor Yellow
    Write-Host ""
    $response = Read-Host "Would you like to reboot now? (Y/N)"
    if ($response -match "^[Yy]") {
        Write-Host "Rebooting system in 10 seconds..." -ForegroundColor Yellow
        shutdown /r /t 10
    } else {
        Write-Host "Please reboot your computer at your earliest convenience." -ForegroundColor Yellow
    }
} else {
    Write-Host "All fixes applied successfully. No reboot required." -ForegroundColor Green
}

Write-Host ""
Write-Host "Run the scanner again to verify fixes:" -ForegroundColor Cyan
Write-Host "  python -m scanner.main" -ForegroundColor White
Write-Host ""
pause
